# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leader.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import node_pb2 as node__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cleader.proto\x1a\nnode.proto\"/\n\x10HeartbeatRequest\x12\x1b\n\x05nodes\x18\x01 \x03(\x0b\x32\x0c.NodeRequest\"%\n\x11HeartbeatResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x81\x01\n\x0eLeaderExchange\x12\x34\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\"\x00\x12\x39\n\x16\x44istributeModelWeights\x12\r.ModelRequest\x1a\x0e.ModelResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leader_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEARTBEATREQUEST._serialized_start=28
  _HEARTBEATREQUEST._serialized_end=75
  _HEARTBEATRESPONSE._serialized_start=77
  _HEARTBEATRESPONSE._serialized_end=114
  _LEADEREXCHANGE._serialized_start=117
  _LEADEREXCHANGE._serialized_end=246
# @@protoc_insertion_point(module_scope)
