# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messages_pb2 as messages__pb2


class ModelExchangeStub(object):
    """the message exchange service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/ModelExchange/RegisterNode',
                request_serializer=messages__pb2.NodeRequest.SerializeToString,
                response_deserializer=messages__pb2.NodeResponse.FromString,
                )
        self.DeregisterNode = channel.unary_unary(
                '/ModelExchange/DeregisterNode',
                request_serializer=messages__pb2.NodeRequest.SerializeToString,
                response_deserializer=messages__pb2.NodeResponse.FromString,
                )
        self.PingLeader = channel.unary_unary(
                '/ModelExchange/PingLeader',
                request_serializer=messages__pb2.NetworkRequest.SerializeToString,
                response_deserializer=messages__pb2.NetworkResponse.FromString,
                )
        self.ShareModelWeights = channel.unary_unary(
                '/ModelExchange/ShareModelWeights',
                request_serializer=messages__pb2.ModelRequest.SerializeToString,
                response_deserializer=messages__pb2.ModelResponse.FromString,
                )


class ModelExchangeServicer(object):
    """the message exchange service definition.
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareModelWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelExchangeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=messages__pb2.NodeRequest.FromString,
                    response_serializer=messages__pb2.NodeResponse.SerializeToString,
            ),
            'DeregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterNode,
                    request_deserializer=messages__pb2.NodeRequest.FromString,
                    response_serializer=messages__pb2.NodeResponse.SerializeToString,
            ),
            'PingLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.PingLeader,
                    request_deserializer=messages__pb2.NetworkRequest.FromString,
                    response_serializer=messages__pb2.NetworkResponse.SerializeToString,
            ),
            'ShareModelWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareModelWeights,
                    request_deserializer=messages__pb2.ModelRequest.FromString,
                    response_serializer=messages__pb2.ModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelExchange', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelExchange(object):
    """the message exchange service definition.
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelExchange/RegisterNode',
            messages__pb2.NodeRequest.SerializeToString,
            messages__pb2.NodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelExchange/DeregisterNode',
            messages__pb2.NodeRequest.SerializeToString,
            messages__pb2.NodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PingLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelExchange/PingLeader',
            messages__pb2.NetworkRequest.SerializeToString,
            messages__pb2.NetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShareModelWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelExchange/ShareModelWeights',
            messages__pb2.ModelRequest.SerializeToString,
            messages__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
